//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenLMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadTbl
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ContactPerson { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public int Value { get; set; }
        public int AssignUser { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string IsActive { get; set; }
    }
}
